id: A0DAF5BAC
title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
type: translation
pechas:
- I39C32C30
- IB4342906
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:06:09.130583
  last_modified_at: 2023-01-04 13:06:09.130590
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I39C32C30/0428: '1691'
  IB4342906/A7AA: '1691'
